#!/usr/bin/env bash
# GENERATED by scripts/generate-ci.py from .github/workflows/ci.yml -- do not edit.
# Usage: scripts/ci.sh [job ...]   (default: all jobs)
# Jobs: lint test
set -euo pipefail
cd "$(dirname "$0")/.."

job_lint() {
  # skipped (runner setup): actions/checkout@v7, cachix/install-nix-action@v31
  (
    set -euo pipefail
    echo "==> lint: Check formatting"
    nix develop --command bash -c "sbt scalafmtCheckAll scalafmtSbtCheck"
    echo "==> lint: Check scripts/ci.sh is up to date"
    nix develop --command bash -c '
      out=$(mktemp) &&
      python3 scripts/generate-ci.py .github/workflows/ci.yml "$out" &&
      diff -u scripts/ci.sh "$out"
    ' || { echo "scripts/ci.sh is stale: run scripts/generate-ci.py and commit" >&2; exit 1; }
  )
}

job_test() {
  # skipped (runner setup): actions/checkout@v7, cachix/install-nix-action@v31
  local failed=0
  echo "### test (scala=2.13.18)"
  (
    set -euo pipefail
    scala=2.13.18
    echo "==> test: Build and Test"
    nix develop --command bash -c "sbt '++${scala}!' clean compile test"
    echo "==> test: Run application"
    nix develop --command bash -c "sbt '++${scala}!' 'run World'"
  ) || { echo "FAILED: test (scala=2.13.18)" >&2; failed=1; }
  echo "### test (scala=3.3.8)"
  (
    set -euo pipefail
    scala=3.3.8
    echo "==> test: Build and Test"
    nix develop --command bash -c "sbt '++${scala}!' clean compile test"
    echo "==> test: Run application"
    nix develop --command bash -c "sbt '++${scala}!' 'run World'"
  ) || { echo "FAILED: test (scala=3.3.8)" >&2; failed=1; }
  return $failed
}

all_jobs=(lint test)
selected=("$@")
[ ${#selected[@]} -gt 0 ] || selected=("${all_jobs[@]}")
status=0
for j in "${selected[@]}"; do
  case " ${all_jobs[*]} " in
    *" $j "*) "job_${j//-/_}" || status=1 ;;
    *) echo "unknown job: $j (available: ${all_jobs[*]})" >&2; exit 2 ;;
  esac
done
exit $status
