#!/usr/bin/env python3
"""Generate scripts/ci.sh from .github/workflows/ci.yml.

Every `run:` step becomes a shell command. `uses:` steps (checkout, nix
install) are skipped since they only prepare the GitHub runner. A job with
`strategy.matrix` becomes a loop over the matrix values, and
`${{ matrix.<key> }}` is rewritten to the shell variable `${<key>}`.

Usage: scripts/generate-ci.py [workflow.yml] [output.sh]
"""
import itertools
import re
import shlex
import stat
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
workflow = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / ".github/workflows/ci.yml"
output = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "scripts/ci.sh"

MATRIX_EXPR = re.compile(r"\$\{\{\s*matrix\.(\w+)\s*\}\}")
ANY_EXPR = re.compile(r"\$\{\{.*?\}\}")


def subst(text, where):
    text = MATRIX_EXPR.sub(lambda m: "${%s}" % m.group(1), text)
    if ANY_EXPR.search(text):
        sys.exit(f"unsupported expression in {where}: {text!r}")
    return text


def job_function(job_id, job):
    matrix = (job.get("strategy") or {}).get("matrix") or {}
    axes = {k: v for k, v in matrix.items() if k not in ("include", "exclude")}
    if "include" in matrix or "exclude" in matrix:
        sys.exit(f"job {job_id}: matrix include/exclude is not supported")
    steps = [s for s in job.get("steps", []) if "run" in s]
    skipped = [s["uses"] for s in job.get("steps", []) if "uses" in s]

    lines = [f"job_{job_id.replace('-', '_')}() {{"]
    if skipped:
        lines.append(f"  # skipped (runner setup): {', '.join(skipped)}")

    def emit(indent):
        pad = "  " * indent
        for i, step in enumerate(steps, 1):
            name = step.get("name") or f"step {i}"
            lines.append(f'{pad}echo "==> {job_id}: {subst(name, job_id)}"')
            for cmd in step["run"].strip().splitlines():
                lines.append(pad + subst(cmd, f"{job_id}/{name}"))

    if not axes:
        # Subshell: `set -e` is ignored inside functions called via `||`.
        lines += ["  (", "    set -euo pipefail"]
        emit(2)
        lines.append("  )")
    else:
        # One subshell per combination; keep going after a failure (fail-fast: false).
        lines.append("  local failed=0")
        keys = list(axes)
        for combo in itertools.product(*(axes[k] for k in keys)):
            assign = " ".join(f"{k}={shlex.quote(str(v))}" for k, v in zip(keys, combo))
            label = ", ".join(f"{k}={v}" for k, v in zip(keys, combo))
            lines.append(f'  echo "### {job_id} ({label})"')
            lines.append(f"  (")
            lines.append("    set -euo pipefail")
            for k, v in zip(keys, combo):
                lines.append(f"    {k}={shlex.quote(str(v))}")
            emit(2)
            lines.append(f'  ) || {{ echo "FAILED: {job_id} ({label})" >&2; failed=1; }}')
        lines.append("  return $failed")
    lines.append("}")
    return lines


def main():
    data = yaml.safe_load(workflow.read_text())
    jobs = data["jobs"]
    ids = list(jobs)
    out = [
        "#!/usr/bin/env bash",
        f"# GENERATED by scripts/generate-ci.py from {workflow.relative_to(ROOT)} -- do not edit.",
        "# Usage: scripts/ci.sh [job ...]   (default: all jobs)",
        f"# Jobs: {' '.join(ids)}",
        "set -euo pipefail",
        'cd "$(dirname "$0")/.."',
        "",
    ]
    for job_id, job in jobs.items():
        out += job_function(job_id, job) + [""]
    out += [
        "all_jobs=(" + " ".join(ids) + ")",
        'selected=("$@")',
        '[ ${#selected[@]} -gt 0 ] || selected=("${all_jobs[@]}")',
        "status=0",
        'for j in "${selected[@]}"; do',
        '  case " ${all_jobs[*]} " in',
        '    *" $j "*) "job_${j//-/_}" || status=1 ;;',
        '    *) echo "unknown job: $j (available: ${all_jobs[*]})" >&2; exit 2 ;;',
        "  esac",
        "done",
        "exit $status",
        "",
    ]
    output.write_text("\n".join(out))
    output.chmod(output.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"wrote {output.relative_to(ROOT) if output.is_relative_to(ROOT) else output}")


main()
