name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-23.11
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build and Test
        run: nix develop --command bash -c "sbt clean compile test"

      - name: Run application
        run: nix develop --command bash -c "sbt 'run World'"
